services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg:
