services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - postgres

volumes:
  pg:
